---
# tasks file for serverTools
- name: 'Role: serverTools Softwares Uteis para administracao do servidor Debian'
  apt:
    update_cache: yes  #Atualiza o packege list
    cache_valid_time: 3600  #1 hora
    name:
      - vim
      - iftop
      - zip
      - wget
      - curl
      - python3

    state: latest
  when: (ansible_facts['os_family'] == "Debian")

- name: 'Role: serverTools Softwares Uteis para administracao do servidor CentOS'
  yum:
    update_cache: yes  #Atualiza o packege list
    cache_valid_time: 3600  #1 hora
    name:
      - vim
      - iftop
      - zip
      - wget
      - curl
      - python3

    state: latest
  when: (ansible_facts['os_family'] == "RedHat")

