---
# handlers file for serverTools
- name: 'addInHostsFile'
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "127.0.0.1 {{ hostname }}"
    - "{{inventory_hostname}} {{ hostname }}"

- name: 'Restart Server'
  reboot: